#!/bin/ash

case "$1" in
    start)
	/bin/mountpoint -q /proc || /bin/mount -t proc none /proc
	/bin/mountpoint -q /sys || /bin/mount -t sysfs sysfs /sys
	;;
    *)
	echo "Usage: $0 {start}" >&2
	exit 1
	;;
esac

exit 0
