#!/bin/sh

# This file is part of the Aloofix project.
# Copyright (C) 2008-2010, 2013 Kevin Johnson <aloof.schipperke@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

diff -u .config.allno .config \
    | grep '^+' | grep -v '^+#' | grep -v '^+$' \
    | grep -v '^+++' | sed -e 's/^+//'
echo CONFIG_MSDOS_PARTITION=y
echo CONFIG_KEYBOARD_ATKBD=y
echo CONFIG_SERIO_LIBPS2=y

exit 0
