#!/bin/sh

# This file is part of the Aloofix project.
# Copyright (C) 2013 Kevin Johnson <aloof.schipperke@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

set -e
set -u

die() { echo "$*" >&2; exit 1; }

[ $# -gt 0 ] || die "usage: $0 pkgname+"
[ -f /etc/aloofix-release ] || die "$0 must be run on an Aloofix machine"

user=$(id -un)
[ "$user" = root ] || die "$0 must be run from the root account"

is_installed() { opkg list-installed | grep -q "^$1 - "; }
is_available() { opkg list | grep -q "^$1 - "; }

do_install() {
    if is_installed "$P"
    then
	echo "$P is already installed"
	return 0
    fi
    is_available "$P" || return 1

    echo "Installing $P"
    opkg install "$P" || die "installation of $P failed"
    is_installed "$1" || die "installation of $1 failed"

    return 0
}

opkg -V 0 update
for P in "$@"
do
    if ! do_install "$P"
    then
	su -c "./scripts/build-pkg '$P'" build || die "build for $P failed"
	opkg -V 0 update
	do_install "$P" || die "build of $P failed or it's not a package"
    fi
done

###############################################################################
