#!/bin/ash

# This file is part of the Aloofix project.
# Copyright (C) 2013 Kevin Johnson <aloof.schipperke@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.


localdir=pkgs
destdir=/srv/www/aloofix

die() { echo "$*" >/dev/tty; exit 1; }

[ -f /etc/aloofix-release ] || die "Don't run $0 on a non-Aloofix machine."

[ -d "$localdir" ] || die "$localdir doesn't exist"
[ -d "$destdir" ] || die "$destdir doesn't exist"

exec rsync -i -a \
    --exclude="*.control" \
    --delay-updates --delete-after \
    "$localdir/" "$destdir"
