#!/bin/ash

/bin/busybox --install -s

boot_scripts="minmount mdev devpts hwclock remount-root hostname modules sysctl find-cdrom mountall"

for boot_script in $boot_scripts
do
    [ -x /etc/init.d/$boot_script ] && /etc/init.d/$boot_script start
done

/bin/dmesg >/var/log/boot.log

/sbin/ifconfig lo 127.0.0.1
/sbin/ip route add 127.0.0.0/8 dev lo
/sbin/udhcpc --now
